name: Check template

on:
  workflow_call:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Compiling lib folder
        run: npm run tsc:lib

      - name: Compiling tests folder
        run: npm run tsc:tests