name: PR check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Check:
    uses: ./.github/workflows/check.yml
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        run: npm run version:check